server:
  port: 8080
spring:
  redis:
    host: 192.168.126.150
    password: 123321
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
